### ISSUE TITLE
Update to Phan version 4?

### ISSUE THREAD

**Issue by 9brada6** [phan/docker#2]
Hi, can this be update to use the version 4 of Phan? Or when using :latest tag to always use the latest Phan?  

When running the latest version it shows:

>  docker run --rm -v ${PWD}:/mnt/src phanphp/phan:latest -v
Phan 3.2.7
php-ast version 1.0.10
PHP version used to run Phan: 7.4.13

**Comment by TysonAndre** [comment]
I'll aim for adding that in 4.0.3 - I was postponing that in case errors were found in early versions of Phan 4
